### PR TITLE
adding delivery configuration

### PR DESCRIPTION
**Pull request by adamleff**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by adamleff** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 656e834d-7a55-4c03-95f1-0e869fcb0ccb approved by: @adamleff

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by adamleff** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 656e834d-7a55-4c03-95f1-0e869fcb0ccb delivered by: @adamleff

**Pull request merged**
